version: 2

jobs:
  test:
    working_directory: ~/rainforestapp/regenwald
    docker:
      - image: circleci/node:8.10.0
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test
